# Generated by Django 4.0.6 on 2022-07-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('numserie', models.IntegerField(primary_key=True, serialize=False)),
                ('idempleado', models.IntegerField()),
                ('lugar', models.IntegerField()),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
    ]
